<?php if(count($this->data)):?>
    <div class="box calendar">
        <div class="main index">
            <div class="header">
                <h3><?php echo $this->translate('Calendar');?></h3>
            </div>
            <div class="content">
                <?php $begin = null;?>
                <?php foreach($this->data as $calendar): ?>
                    <?php if ($calendar->begin != $begin):?>
                        <?php if ($begin != null):?>
                            </ul></div>
                        <?php endif;?>
                        <div class="item">
                            <div class="date">
                                <div><?php echo date('d', strtotime($calendar->begin))?></div>
                                <div><?php echo $this->translate(date('M', strtotime($calendar->begin)))?></div>
                            </div>
                            <ul>
                    <?php endif;?>
                    <li>
                        <?php echo $calendar->description?>
                        <?php $begin = $calendar->begin;?>
                    </li>
                <?php endforeach;?>
                        </ul></div>
                <div class="clear">
                    <a href="calendar"><?php echo $this->translate('View all');?></a>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>